### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
"fullname": "Tyr Chen", "email": "tchen@acme.org", "password": "123456", "workspace": "acme"
}

### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
"fullname": "Alice Chen", "email": "alice@acme.org", "password": "123456", "workspace": "test"
}

### signin user (invalid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

### signin user (valid)

# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}




### create chat
@token = {{signin.response.body.token}}
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}
### update chat
@token = {{signin.response.body.token}}
PATCH http://localhost:6688/api/chats/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acme",
    "members": [1, 2],
    "public": false,
    "id": 12
}

### delete chat
@token = {{signin.response.body.token}}
DELETE  http://localhost:6688/api/chats/12
Content-Type: application/json
Authorization: Bearer {{token}}

### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="rust-logo.png"
Content-Type: application/octet-stream

< /home/l/downloads/rust-logo.png
--MyBoundary
Content-Disposition: form-data; name="file"; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--


### get files png

GET http://localhost:6688/api/files/2/365/67d/b987f7a96feff1947d2611879c831d805b.png
Authorization: Bearer {{token}}

### get files txt
GET http://localhost:6688/api/files/2/0a0/a9f/2a6772942557ab5355d76af442f8f65e01.txt
Authorization: Bearer {{token}}


### send a message

POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello, alice!",
    "files": []
}

### get messages

GET http://localhost:6688/api/chats/1/messages?limit=10&last_id=20
Authorization: Bearer {{token}}
